sudo: required
services:
  - docker

before_install:
  - docker build -t rahuldaware1991/docker-react -f Dockerfile.dev .

script:
  - docker run rahuldaware1991/docker-react npm run test -- --coverage